# Generated by Django 2.2.1 on 2019-12-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herokuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_ticket', models.IntegerField(default=0)),
                ('coupon', models.CharField(max_length=10)),
                ('payment_type', models.IntegerField(default=0)),
                ('payment_status', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.Trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.User')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='herokuapp.Booking'),
            preserve_default=False,
        ),
    ]
