# Generated by Django 2.2.1 on 2019-12-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herokuapp', '0002_auto_20191210_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
